app/routes/product.py
from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required
from app import db
from app.models import Product

product = Blueprint('product', __name__)


@product.route('/products')
@login_required
def products():
    page = request.args.get('page', 1, type=int)
    all_products = Product.query.paginate(page=page, per_page=10, error_out=False)
    return render_template('products.html', products=all_products.items, pagination=all_products)


@product.route('/add-product', methods=['POST'])
def add_product():
    name = request.form['name']
    price = request.form['price']
    quantity = request.form['quantity']
    manufacturer = request.form['manufacturer']

    new_product = Product(name=name, price=price, quantity=quantity, manufacturer=manufacturer)
    db.session.add(new_product)
    db.session.commit()

    return jsonify({"success": True, "message": "Product added successfully"})


@product.route('/delete-product/<int:product_id>', methods=['DELETE'])
def delete_product(product_id):
    found_product = Product.query.get(product_id)
    if found_product:
        db.session.delete(found_product)
        db.session.commit()
        return jsonify({'success': True, 'message': 'Product has been deleted.'}), 200
    else:
        return jsonify({'error': 'Product not found'}), 404


@product.route('/update-product/<int:product_id>', methods=['POST'])
def update_product(product_id):
    found_product = Product.query.get(product_id)
    if found_product:
        found_product.name = request.form['name']
        found_product.price = request.form['price']
        found_product.quantity = request.form['quantity']
        found_product.manufacturer = request.form['manufacturer']

        db.session.commit()
        return jsonify({'success': True, 'message': 'Product has been updated.'}), 200
    else:
        return jsonify({'error': 'Product not found'}), 404

app/routes/users.py
from flask import Blueprint, render_template, request

from app.models import User
from app.validation.roles import admin_required

users = Blueprint('users', __name__)


@users.route('/users')
@admin_required
def users_list():
    page = request.args.get('page', 1, type=int)
    all_users = User.query.paginate(page=page, per_page=10, error_out=False)
    return render_template('users.html', users=all_users.items, pagination=all_users)

app/templates/_base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Title{% endblock %}</title>
  {% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='/css/global.css') }}">
    <script src="{{ url_for('static', filename='/js/tailwindcss.js') }}"></script>
  {% endblock %}
</head>
<body>
<div class="flex flex-col h-full">
  <nav class="lg:px-16 px-4 bg-white flex flex-wrap items-center py-4 shadow-md">
    {% block nav %}
      <div class="flex-1 flex justify-between items-center">
        <a href="/" class="text-xl">Storage</a>
      </div>
      <div class="hidden md:flex md:items-center md:w-auto w-full" id="menu">
        <nav>
          <ul class="md:flex items-center justify-between text-base text-gray-700 pt-4 md:pt-0">
            <li>
              <a class="md:p-4 py-3 px-0 block {{ 'text-blue-500 font-bold' if request.path == '/' }}"
                 href="/">Home</a>
            </li>
            <li>
              <a class="md:p-4 py-3 px-0 block {{ 'text-blue-500 font-bold' if request.path == '/blog' }}"
                 href="/blog">Blog</a>
            </li>
            {% if current_user.is_authenticated %}
              <li><a
                class="md:p-4 py-3 px-0 block {{ 'text-blue-500 font-bold' if request.path == '/products' else '' }}"
                href="/products">Products</a>
                {% if current_user.role_name == 'admin' %}
                  <li><a class="md:p-4 py-3 px-0 block {{ 'text-blue-500 font-bold' if request.path == '/users' }}"
                         href="/users">Users</a></li>
                {% endif %}
              <li><a class="md:p-4 py-3 px-0 block {{ 'text-blue-500 font-bold' if request.path == '/logout' }}"
                     href="/logout">Logout</a>

                {% else %}
              <li><a class="md:p-4 py-3 px-0 block {{ 'text-blue-500 font-bold' if request.path == '/login' }}"
                     href="/login">Login</a></li>
              <li><a
                class="md:p-4 py-3 px-0 block md:mb-0 mb-2 {{ 'text-blue-500 font-bold' if request.path == '/register' }}"
                href="/register">Register</a></li>
            {% endif %}

          </ul>
        </nav>
      </div>

    {% endblock %}
  </nav>

  {% block header %}
  {% endblock %}

  {% block content %}
  {% endblock %}

  {% block footer %}
  {% endblock %}

  {% block script %}
  {% endblock %}
</div>
</body>
</html>

app/templates/index.html
{% extends '_base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
   <h1>Home</h1>
{% endblock %}

app/templates/login.html
{% extends '_base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <div class="h-full bg-gray-100">
    <div class="h-4/5 sm:container lg:px-20 mx-auto flex items-center justify-center ">
      <div class="px-8 py-6 mt-4 text-left bg-white shadow-lg">
        <h3 class="text-2xl font-bold text-center">Login to your account</h3>
        <form method="post">
          {{ form.hidden_tag() }}
          <div class="mt-4">
            <div>
              {{ form.username.label(class="block", for="username") }}
              {{ form.username(class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600", placeholder="Username") }}
              {% if form.username.errors %}
                {% for error in form.username.errors %}
                  <div class="text-sm text-red-600">{{ error }}</div>
                {% endfor %}
              {% endif %}
            </div>
            <div class="mt-4">
              {{ form.password.label(class="block") }}
              {{ form.password(placeholder="Password", class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600") }}
              {% if form.password.errors %}
                {% for error in form.password.errors %}
                  <div class="text-sm text-red-600">{{ error }}</div>
                {% endfor %}
              {% endif %}
            </div>
            <div class="my-4">
              {{ form.remember_me(class="form-check-input") }}
              {{ form.remember_me.label(class="form-check-label") }}
            </div>
            <div class="flex  justify-between">
              {{ form.submit(class="px-6 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-900 w-full") }}
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/products.html
{% extends "_base.html" %}
{% block content %}
  <div class="sm:container lg:px-20 mx-auto ">
    <div class="flex justify-between border-b-2 pb-2 my-4">
      <h1 class="text-4xl font-bold">Products</h1>
      <button class="px-6 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-900 " onclick="openAddModal()">Add
        Product
      </button>
    </div>

    <div class=" max-h-[450px] overflow-y-auto shadow-md my-4">
      <table class="w-full  text-sm text-left rtl:text-right text-gray-500 ">
        <thead class="text-xs sticky top-0 text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3 text-center">
            #
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Product name
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Price
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Quantity
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Manufacturer
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Actions
          </th>
        </tr>
        </thead>
        <tbody>
        {% for product in products %}
          <tr class="bg-white border-b hover:bg-gray-50 ">
            <td class="px-6 py-2 text-center">{{ loop.index }}</td>
            <td class="px-6 py-2 text-center">{{ product.name }}</td>
            <td class="px-6 py-2 text-center">{{ product.price }}</td>
            <td class="px-6 py-2 text-center">{{ product.quantity }}</td>
            <td class="px-6 py-2 text-center">{{ product.manufacturer }}</td>
            <td class="flex gap-4 px-6 py-2 text-center">
              <button class="px-6 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-900"
                      onclick="openEditModal({{ product.id }})">Edit
              </button>
              <button class="px-6 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-900"
                      onclick="openDeleteModal({{ product.id }})">Delete
              </button>
            </td>
          </tr>
        {% else %}
          <td colspan="5" class="px-6 py-2 text-center">Products not found</td>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="w-full flex items-center justify-center pb-4">
    {% if pagination.pages > 1 %}
      <ul class="flex items-center -space-x-px h-10 text-base">
        {% if pagination.has_prev %}
          <li>
          <a href="{{ url_for('product.products', page=pagination.prev_num) }}"
             class="flex items-center justify-center px-4 h-10 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700">
            <span class="sr-only">Previous</span>
            <svg class="w-3 h-3 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                 viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M5 1 1 5l4 4"></path>
            </svg>
          </a>
        {% endif %}

        {% for page in pagination.iter_pages() %}
          {% if page %}
            {% if page != pagination.page %}
              <li><a href="{{ url_for('product.products', page=page) }}"
                     class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700">{{ page }}</a>
              </li>
            {% else %}
              <li>
                <span
                  class="z-10 flex items-center justify-center px-4 h-10 leading-tight text-blue-600 border border-blue-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700">{{ page }}</span>
              </li>
            {% endif %}
          {% endif %}
        {% endfor %}


        {% if pagination.has_next %}
          <li><a href="{{ url_for('product.products', page=pagination.next_num) }}"
                 class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700">
            <span class="sr-only">Next</span>
            <svg class="w-3 h-3 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                 viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="m1 9 4-4-4-4"></path>
            </svg>
          </a></li>
        {% endif %}

      </ul>
    {% endif %}
  </div>


  {% include 'modals/add_product_modal.html' %}
  {% include 'modals/delete_product_modal.html' %}
  {% include 'modals/edit_product_modal.html' %}


{% endblock %}

app/templates/register.html
{% extends '_base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
  <div class="h-full bg-gray-100">
    <div class="h-[90%] sm:container lg:px-20 mx-auto flex items-center justify-center ">
      <div class="px-8 py-6 mt-4 text-left bg-white shadow-lg">
        <h3 class="text-2xl font-bold text-center">Register account</h3>
        <form method="POST">
          {{ form.hidden_tag() }}
          <div class="mt-4">
            <div>
              {{ form.username.label(class="block", for="username") }}
              {{ form.username(class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600", placeholder="Username") }}
              {% if form.username.errors %}
                {% for error in form.username.errors %}
                  <div class="text-sm text-red-600">{{ error }}</div>
                {% endfor %}
              {% endif %}
            </div>
            <div class="mt-4">
              {{ form.email.label(class="block", for="email") }}
              {{ form.email(class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600", placeholder="Email") }}
              {% if form.email.errors %}
                {% for error in form.email.errors %}
                  <div class="text-sm text-red-600">{{ error }}</div>
                {% endfor %}
              {% endif %}
            </div>
            <div class="mt-4">
              {{ form.password.label(class="block") }}
              {{ form.password(placeholder="Password", class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600") }}
              {% if form.password.errors %}
                {% for error in form.password.errors %}
                  <div class="text-sm text-red-600">{{ error }}</div>
                {% endfor %}
              {% endif %}
            </div>
            <div class="mt-4">
              {{ form.password2.label(class="block") }}
              {{ form.password2(placeholder="Confirm password", class="w-full px-4 py-2 mt-2 border rounded-md focus:outline-none focus:ring-1 focus:ring-blue-600") }}
              {% if form.password2.errors %}
                {% for error in form.password2.errors %}
                  <div class="text-sm text-red-600">{{ error }}</div>
                {% endfor %}
              {% endif %}
            </div>
            <div class="flex mt-4 justify-between">
              {{ form.submit(class="px-6 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-900 w-full") }}
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/users.html
{% extends "_base.html" %}
{% block content %}
  <div class="sm:container lg:px-20 mx-auto ">
    <div class="flex justify-between border-b-2 pb-2 my-4">
      <h1 class="text-4xl font-bold">Users</h1>
      <button class="px-6 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-900 " onclick="">
        Add User
      </button>
    </div>

    <div class=" max-h-[450px] overflow-y-auto shadow-md my-4">
      <table class="w-full  text-sm text-left rtl:text-right text-gray-500 ">
        <thead class="text-xs sticky top-0 text-gray-700 uppercase bg-gray-50">
        <tr>
          <th scope="col" class="px-6 py-3 text-center">
            #
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Username
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Email
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Quantity
          </th>
          <th scope="col" class="px-6 py-3 text-center">
            Actions
          </th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
          <tr class="bg-white border-b hover:bg-gray-50 ">
            <td class="px-6 py-2 text-center">{{ loop.index }}</td>
            <td class="px-6 py-2 text-center">{{ user.username }}</td>
            <td class="px-6 py-2 text-center">{{ user.email }}</td>
            <td class="px-6 py-2 text-center">{{ user.role.name|capitalize }}</td>
            <td class="flex gap-4 px-6 py-2 text-center">
              <button class="px-6 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-900"
                      onclick="">Edit
              </button>
              <button class="px-6 py-2 text-white bg-blue-600 rounded-lg hover:bg-blue-900"
                      onclick="">Delete
              </button>
            </td>
          </tr>
        {% else %}
          <td colspan="5">Users not found</td>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

  <div class="w-full flex items-center justify-center pb-4">
    {% if pagination.pages > 1 %}
      <ul class="flex items-center -space-x-px h-10 text-base">
        {% if pagination.has_prev %}
          <li>
          <a href="{{ url_for('users.users', page=pagination.prev_num) }}"
             class="flex items-center justify-center px-4 h-10 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700">
            <span class="sr-only">Previous</span>
            <svg class="w-3 h-3 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                 viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M5 1 1 5l4 4"></path>
            </svg>
          </a>
        {% endif %}

        {% for page in pagination.iter_pages() %}
          {% if page %}
            {% if page != pagination.page %}
              <li><a href="{{ url_for('users.users', page=page) }}"
                     class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700">{{ page }}</a>
              </li>
            {% else %}
              <li>
                <span
                  class="z-10 flex items-center justify-center px-4 h-10 leading-tight text-blue-600 border border-blue-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700">{{ page }}</span>
              </li>
            {% endif %}
          {% endif %}
        {% endfor %}


        {% if pagination.has_next %}
          <li><a href="{{ url_for('users.users', page=pagination.next_num) }}"
                 class="flex items-center justify-center px-4 h-10 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700">
            <span class="sr-only">Next</span>
            <svg class="w-3 h-3 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                 viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="m1 9 4-4-4-4"></path>
            </svg>
          </a></li>
        {% endif %}

      </ul>
    {% endif %}
  </div>


{#  {% include 'modals/add_product_modal.html' %}#}
{#  {% include 'modals/delete_product_modal.html' %}#}
{#  {% include 'modals/edit_product_modal.html' %}#}


{% endblock %}